### ISSUE TITLE
老大 更新一下框架嘛

### ISSUE THREAD

**Issue by mojunyu** [fuchaoqun/colaphp#10]

**Comment by fuchaoqun** [comment]
抱歉，最近colaphp的更新非常缓慢了，主要是因为我没有想好该怎么迭代。

早年的colaphp主要受zend framework和django影响，解决的是zend framework慢以及复杂的问题，全面拥抱array，追求极致的性能以及简便的开发特性。这几年开始更多的关注其他语言，逐步认识到应该在语言层面应该做更多的工作。

现在的php已经很快了，拥抱array而不是对象带来很多编程上的麻烦（如key的拼写问题），也可以全面拥抱面向对象，估计就是下一个laravel或者spring boot，和我最开始想解决的初衷又不一样了。

我还没想好怎么做下一个迭代，也许我们应该在另外的一个层面去思考编程语言和编程框架的问题，如果有bug什么的，我会及时修复。

感谢。

**Comment by mojunyu** [comment]
哈哈好的 感谢大佬回复！
