### ISSUE TITLE
config.php文件的_merge方法的BUG

### ISSUE THREAD

**Issue by zhuzhichao** [fuchaoqun/colaphp#7]
通过该方法合并类似下面两个数组时：

<pre><code>
$arr1 = [
    'name' => 'Tom',
    'info' => 'thing'
];

$arr2 = [
    'name' => 'Jack',
    'info' => [
        'addr' => 'beijing',
        'age'  => '18'
    ]
];
</code></pre>

得到的结果是：

<pre><code>
array (size=2)
  'name' => string 'Jack' (length=4)
  'info' => string '1hing' (length=5)
</code></pre>

建议：_merge方法中应该增加个逻辑判断$arr1为字符串的情况，直接返回$arr2的值即可。

**Comment by fuchaoqun** [comment]
这种情况太复杂了，merge本意就是为了合并数组的，字符串和数据的合并，这个还是交给工程师自己控制吧。
