### ISSUE TITLE
新框架ColaPHP

### ISSUE THREAD

**Issue by josark2005** [fuchaoqun/colaphp#8]
作者大大，我是[Twocola PHP Engine（也称TCE）](https://github.com/jokin1999/TwocolaPHPEngine/)框架的作者。
想在TCE4.2版本后改名叫ColaPHP，百度一查有你的一个年久失修的作品，想与作者合作完成一个新的PHP框架。
可以到我的仓库里看一看[TCE的一些手册](http://tce.twocola.com)，TCE是一个不成熟的作品，但是我感觉已经达到可运营的水平了。
最后希望能得到你的回复，若没有回复的话我就是用ColaPHP这个名称了，如果有任何不满，请随时联系我！再次希望能与你合作！

**Comment by fuchaoqun** [comment]
你好，

colaphp 我还一直在开发维护，只是比较稳定了，更新的比较少。



2017-08-12 21:32 GMT+08:00 Jokin惟易 <notifications@github.com>:
